/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DnVjEy7Ev7B
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"

export function Login() {
  return (
    <div className="flex flex-col gap-2 min-h-screen items-center justify-center p-6 lg:gap-4 lg:flex-row">
      <div className="w-full max-w-[400px] space-y-4">
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your email below to login to your account</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" required type="email" />
          </div>
          <div className="space-y-2">
            <div className="flex items-center">
              <Label htmlFor="password">Password</Label>
              <Link className="ml-auto inline-block text-sm underline" href="#">
                Forgot your password?
              </Link>
            </div>
            <Input id="password" required type="password" />
          </div>
          <div className="space-y-2">
            <Button className="w-full" type="submit">
              Login
            </Button>
            <div className="flex items-center space-x-2 text-sm">
              <Checkbox id="remember-me" />
              <Label className="text-sm" htmlFor="remember-me">
                Remember me
              </Label>
            </div>
          </div>
        </div>
        <div className="mt-4 text-center text-sm">
          Don't have an account?
          <Link className="underline" href="#">
            Sign up
          </Link>
        </div>
      </div>
      <div className="w-full border-t/2 dark:border-t/gray-800 lg:max-w-[400px] xl:max-w-[500px]" />
    </div>
  )
}
